-- Creating tables for final_project_draft
CREATE TABLE listings (
	id int PRIMARY KEY,
	listing_url varchar,
	scrape_id varchar,
	last_scraped date,
	name varchar,
	summary varchar,
	space varchar,
	description varchar,
	experiences_offered varchar,
	neighborhood_overview varchar,
	notes varchar,
	transit varchar,
	thumbnail_url varchar,
	medium_url varchar,
	picture_url varchar,
	xl_picture_url varchar,
	host_id int,
	host_url varchar,
	host_name varchar,
	host_since date,
	host_location varchar,
	host_about varchar,
	host_response_time varchar,
	host_response_rate decimal,
	host_acceptance_rate decimal,
	host_is_superhost varchar(1),
	host_thumbnail_url varchar,
	host_picture_url varchar,
	host_neighbourhood varchar,
	host_listings_count int,
	host_total_listings_count int,
	host_verifications varchar,
	host_has_profile_pic varchar(1),
	host_identity_verified varchar(1),
	street varchar,
	neighbourhood varchar,
	neighbourhood_cleansed varchar,
	neighbourhood_group_cleansed varchar,
	city varchar,
	state varchar(2),
	zipcode char(5),
	market varchar,
	smart_location varchar,
	country_code varchar(2),
	country varchar,
	latitude decimal,
	longitude decimal,
	is_location_exact varchar(1),
	property_type varchar,
	room_type varchar,
	accommodates int,
	bathrooms decimal,
	bedrooms int,
	beds int,
	bed_type varchar,
	amenities varchar,
	square_feet int,
	price decimal,
	weekly_price decimal,
	monthly_price decimal,
	security_deposit decimal,
	cleaning_fee decimal,
	guests_included int,
	extra_people decimal,
	minimum_nights int,
	maximum_nights int,
	calendar_updated varchar,
	has_availability varchar(1),
	availability_30 int,
	availability_60 int,
	availability_90 int,
	availability_365 int,
	calendar_last_scraped date,
	number_of_reviews int,
	first_review date,
	last_review date,
	review_scores_rating int,
	review_scores_accuracy int,
	review_scores_cleanliness int,
	review_scores_checkin int,
	review_scores_communication int,
	review_scores_location int,
	review_scores_value int,
	requires_license varchar(1),
	license varchar,
	jurisdiction_names varchar,
	instant_bookable varchar(1),
	cancellation_policy varchar,
	require_guest_profile_picture varchar(1),
	require_guest_phone_verification varchar(1),
	calculated_host_listings_count int,
	reviews_per_month decimal
);

CREATE TABLE calendar (
	id SERIAL PRIMARY KEY,
	listing_id int REFERENCES listings(id),
	date date,
	available varchar(1),
	price decimal
);	
	
CREATE TABLE reviews (
	listing_id int REFERENCES listings(id),
	id int PRIMARY KEY,
	date date,
	reviewer_id int,
	reviewer_name varchar,
	comments varchar
);

